name: build-env
channels:
  - conda-forge
dependencies:
  - python >=3.11
  - pip
  - jupyter_server
  - jupyterlite-core >=0.7
  - jupyterlite-xeus >=4.3
  - notebook >=7.5
  - specta
  - pip:
      - jupyterlite-ai
